<?php
// $Id: belead_product.module,v 1.26 2008/01/19 21:13:58 bdragon Exp $

/**
 * Implementation of hook_node_info(). This function replaces hook_node_name()
 * and hook_node_types() from 4.6. Drupal 5 expands this hook significantly.
 *
 * This is a required node hook. This function describes the nodes provided by
 * this module.
 *
 * The required attributes are:
 * - "name" provides a human readable name for the node,
 * - "module" tells Drupal how the module's functions map to hooks (i.e. if the
 *   module is belead_product_foo then belead_product_foo_insert will be called
 *   when inserting the node).
 * - "description" provides a brief description of the node type, which is
 *   show up when a user accesses the "Create content" page for that node type.
 *
 * The other optional, attributes:
 * - "has_title" boolean that indicates whether or not this node type has a
 *   title field.
 * - "title_label": the label for the title field of this content type.
 * - "has_body": boolean that indicates whether or not this node type has a
 *   body field.
 * - "body_label": the label for the body field of this content type.
 * - "min_word_count": the minimum number of words for the body field to be
 *   considered valid for this content type.
 */
define(BELEAD_PRODUCT_CREATE_CONTENT, 'create belead product content');
define(BELEAD_PRODUCT_EDIT_ANY_CONTENT, 'edit any belead product content');
define(BELEAD_PRODUCT_EDIT_OWN_CONTENT, 'edit own belead product content');
define(BELEAD_PRODUCT_DELETE_ANY_CONTENT, 'delete any belead product content');
define(BELEAD_PRODUCT_DELETE_OWN_CONTENT, 'delete own belead product content');
define(BELEAD_PRODUCT_MANAGE, 'manage belead product');

function belead_product_node_info()
{
	return array (
			'belead_product' => array(
				'name' => t('Belead Product'),
				'module' => 'belead_product',
				'description' => t("This is belead product node type."),
				'has_title' => TRUE,
				'title_label' => t('Page Title'),
				'has_body' => TRUE,
				'body_label' => t('Page Body'),
				)
		    );
}

/**
 * Implementation of hook_access().
 *
 * Node modules may implement node_access() to determine the operations
 * users may perform on nodes. This example uses a very common access pattern.
 */
function belead_product_access($op, $node, $account)
{
	if ($op == 'create') {
		return user_access(BELEAD_PRODUCT_CREATE_CONTENT, $account);
	}

	if ($op == 'update') {
		if (user_access(BELEAD_PRODUCT_EDIT_ANY_CONTENT, $account) || (user_access(BELEAD_PRODUCT_EDIT_OWN_CONTENT, $account) && ($account->uid == $node->uid))) {
			return TRUE;
		}
	}

	if ($op == 'delete') {
		if (user_access(BELEAD_PRODUCT_DELETE_ANY_CONTENT, $account) || (user_access(BELEAD_PRODUCT_DELETE_OWN_CONTENT, $account) && ($account->uid == $node->uid))) {
			return TRUE;
		}
	}
}

/**
 * Implementation of hook_perm().
 *
 * Since we are limiting the ability to create new nodes to certain users,
 * we need to define what those permissions are here. We also define a permission
 * to allow users to edit the nodes they created.
 */
function belead_product_perm()
{
	return array(
			BELEAD_PRODUCT_CREATE_CONTENT,
			BELEAD_PRODUCT_EDIT_ANY_CONTENT,
			BELEAD_PRODUCT_EDIT_OWN_CONTENT,
			BELEAD_PRODUCT_DELETE_ANY_CONTENT,
			BELEAD_PRODUCT_DELETE_OWN_CONTENT,
			BELEAD_PRODUCT_MANAGE,
		    );
}

/**
 * Implementation of hook_form().
 *
 * Now it's time to describe the form for collecting the information
 * specific to this node type. This hook requires us to return an array with
 * a sub array containing information for each element in the form.
 */
function belead_product_form(&$node)
{
	// The site admin can decide if this node type has a title and body, and how
	// the fields should be labeled. We need to load these settings so we can
	// build the node form correctly.
	$type = node_get_types('type', $node);

	if ($type->has_title) {
		$form['title'] = array(
				'#type' => 'textfield',
				'#title' => check_plain($type->title_label),
				'#required' => TRUE,
				'#default_value' => $node->title,
				'#weight' => -5
				);
	}

	if ($type->has_body) {
		// In Drupal 6, we can use node_body_field() to get the body and filter
		// elements. This replaces the old textarea + filter_form() method of
		// setting this up. It will also ensure the teaser splitter gets set up
		// properly.
		$form['body_field'] = node_body_field($node, $type->body_label, $type->min_word_count);
	}

	$form['category_name'] = array(
			'#type' => 'textfield',
			'#title' => t('Category Name'),
			'#default_value' => isset($node->category_name) ? $node->category_name : '',
			'#size' => 80,
			'#maxlength' => 80
			);

	$form['application_area'] = array(
			'#type' => 'textfield',
			'#title' => t('Application Area'),
			'#default_value' => isset($node->application_area) ? $node->application_area : '',
			'#size' => 80,
			'#maxlength' => 80
			);

	$form['category_description'] = array(
			'#type' => 'textarea',
			'#title' => t('Category Description'),
			'#default_value' => isset($node->category_description) ? $node->category_description : '',
			);

	return $form;
}

/**
 * Implementation of hook_validate().
 *
 * Our "quantity" field requires a number to be entered. This hook lets
 * us ensure that the user entered an appropriate value before we try
 * inserting anything into the database.
 *
 * Errors should be signaled with form_set_error().
 */
function belead_product_validate(&$node)
{
}

/**
 * Implementation of hook_insert().
 *
 * As a new node is being inserted into the database, we need to do our own
 * database inserts.
 */
function belead_product_insert($node)
{
	db_query("INSERT INTO {belead_product} (vid, nid, category_name, application_area, category_description) VALUES (%d, %d, '%s', '%s', '%s')", $node->vid, $node->nid, $node->category_name, $node->application_area, $node->category_description);
}

/**
 * Implementation of hook_update().
 *
 * As an existing node is being updated in the database, we need to do our own
 * database updates.
 */
function belead_product_update($node)
{
	// if this is a new node or we're adding a new revision,
	if ($node->revision) {
		belead_product_insert($node);
	} else {
		db_query("UPDATE {belead_product} SET category_name = '%s', application_area = '%s', category_description = '%s' WHERE vid = %d", $node->category_name, $node->application_area, $node->category_description, $node->vid);
	}
}

/**
 * Implementation of hook_nodeapi().
 *
 * When a node revision is deleted, we need to remove the corresponding record
 * from our table. The only way to handle revision deletion is by implementing
 * hook_nodeapi().
 */
function belead_product_nodeapi(&$node, $op, $teaser, $page)
{
	switch ($op) {
		case 'delete revision':
			// Notice that we're matching a single revision based on the node's vid.
			db_query('DELETE FROM {belead_product} WHERE vid = %d', $node->vid);
			break;
	}
}

/**
 * Implementation of hook_delete().
 *
 * When a node is deleted, we need to remove all related records from out table.
 */
function belead_product_delete($node)
{
	// Notice that we're matching all revision, by using the node's nid.
	db_query('DELETE FROM {belead_product} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 *
 * Now that we've defined how to manage the node data in the database, we
 * need to tell Drupal how to get the node back out. This hook is called
 * every time a node is loaded, and allows us to do some loading of our own.
 */
function belead_product_load($node)
{
	$additions = db_fetch_object(db_query('SELECT * FROM {belead_product} WHERE vid = %d', $node->vid));
	return $additions;
}

/**
 * Implementation of hook_view().
 *
 * This is a typical implementation that simply runs the node text through
 * the output filters.
 */
function belead_product_view($node, $teaser = FALSE, $page = FALSE)
{
	global $user, $base_url;
	$node = node_prepare($node, $teaser);

	/* Full node content view */
	drupal_set_title(theme('belead_product_page_title', $node));
	if (user_access(BELEAD_PRODUCT_MANAGE)) {
		$node->content['belead_product_script'] = array (
				'#value' => theme('belead_product_script', $node),
				'#weight' => 1
				);
	}
	if (isset($_GET['product_id'])) {
		if ($_GET['action'] == 'edit') {
			$form = drupal_get_form('belead_product_edit_form', $node);
			$node->content['belead_product_edit'] = array (
					'#value' => $form,
					'#weight' => 2
					);
		} elseif ($_GET['action'] == 'delete') {
			$form = drupal_get_form('belead_product_delete_form', $node);
			$node->content['belead_product_delete'] = array (
					'#value' => $form,
					'#weight' => 2
					);
		} else {
			$node->content['belead_product_main'] = array (
					'#value' => theme('belead_product_main', $node),
					'#weight' => 2
					);
		}
	} else {
		$node->content['belead_product_category_main'] = array (
				'#value' => theme('belead_product_category_main', $node),
				'#weight' => 2
				);
		if (user_access(BELEAD_PRODUCT_MANAGE)) {
			$form = drupal_get_form('belead_product_category_edit_form', $node);
			$node->content['belead_product_category_edit'] = array (
					'#value' => $form,
					'#weight' => 3
					);
			$form = drupal_get_form('belead_product_add_form', $node);
			$node->content['belead_product_add'] = array (
					'#value' => $form,
					'#weight' => 4
					);
		}
	}
	return $node;
}

function belead_product_category_edit_form($form_state, $node)
{ 
	$result = db_query('select * from belead_product where vid = %d', $node->vid);
	$row = db_fetch_array($result);
	$form = array ();
	$form['belead_product_category_edits'] = array (
			'#type' => 'fieldset',
			'#title' => t('Edit Category'),
			'#collapsible' => TRUE,
			'#collapsed' => TRUE,
			'#prefix' => '<div class="belead_product_category_edit_form">',
			'#suffix' => '</div>',
			'#weight' => 30
			);
	$form['#node']= $node;
	$form['#attributes'] = array (
			'enctype' => "multipart/form-data"
			);
	$form['#validate'][] = 'belead_product_category_edit_form_validate';
	$form['belead_product_category_edits']['belead_product_category_name'] = array (
			'#type' => 'textfield',
			'#title' => t('Category Name'),
			'#default_value' => $row['category_name'],
			'#size' => 85
			);
	$form['belead_product_category_edits']['belead_product_application_area'] = array (
			'#type' => 'textfield',
			'#title' => t('Application Area'),
			'#default_value' => $row['application_area'],
			'#size' => 85
			);
	$form['belead_product_category_edits']['belead_product_category_description'] = array (
			'#type' => 'textarea',
			'#resizable' => FALSE,
			'#title' => t('Description'),
			'#default_value' => $row['category_description'],
			'#size' => 255
			);
	$form['submitted'] = array (
			'#tree' => TRUE
			);
	$form['belead_product_category_edits']['belead_product_button_edit'] = array (
			'#type' => 'submit',
			'#value' => t('Update'),
			'#name' => 'update',
			'#submit' => array('belead_product_category_edit_form_submit_update')
			);
	$form['belead_product_category_edits']['belead_product_button_cancel'] = array (
			'#type' => 'submit',
			'#value' => t('Cancel'),
			'#name' => 'cancel',
			'#submit' => array('belead_product_category_edit_form_submit_cancel')
			);
	$form['belead_product_category_edits']['belead_product_hidden'] = array (
			'#type' => 'hidden',
			'#value' => $node->vid,
			'#name' => 'hidden'
			);
	return $form;
}

function belead_product_category_edit_form_validate($form, & $form_state)
{
}

function belead_product_category_edit_form_submit_update($form, & $form_state)
{
	$name = $form_state['values']['belead_product_category_name'];
	$area = $form_state['values']['belead_product_application_area'];
	$description = $form_state['values']['belead_product_category_description'];
	$id = $form_state['values']['belead_product_hidden'];
	db_query("update belead_product set category_name = '%s', application_area = '%s', category_description = '%s' where vid = %d", $name, $area, $description, $id);
}

function belead_product_category_edit_form_submit_cancel($form, & $form_state)
{
}

function belead_product_add_form($form_state, $node)
{ 
	$form = array ();
	$form['belead_product_adds'] = array (
			'#type' => 'fieldset',
			'#title' => t('Add Product'),
			'#collapsible' => TRUE,
			'#collapsed' => TRUE,
			'#prefix' => '<div class="belead_product_add_form">',
			'#suffix' => '</div>',
			'#weight' => 30
			);
	$form['#node']= $node;
	$form['#attributes'] = array (
			'enctype' => "multipart/form-data"
			);
	$form['#validate'][] = 'belead_product_add_form_validate';
	$form['belead_product_adds']['belead_product_name'] = array (
			'#type' => 'textfield',
			'#title' => t('Name'),
			'#size' => 85
			);
	$form['belead_product_adds']['belead_product_picture'] = array (
			'#type' => 'file',
			'#title' => t('Picture'),
			'#size' => 40
			);
	$form['belead_product_adds']['belead_product_description'] = array (
			'#type' => 'textarea',
			'#resizable' => FALSE,
			'#title' => t('Description'),
			'#size' => 255
			);
	$form['submitted'] = array (
			'#tree' => TRUE
			);
	$form['belead_product_adds']['belead_product_button_add'] = array (
			'#type' => 'submit',
			'#value' => t('Add'),
			'#name' => 'add',
			'#submit' => array('belead_product_add_form_submit_add')
			);
	$form['belead_product_adds']['belead_product_button_cancel'] = array (
			'#type' => 'submit',
			'#value' => t('Cancel'),
			'#name' => 'cancel',
			'#submit' => array('belead_product_add_form_submit_cancel')
			);
	$form['belead_product_adds']['belead_product_hidden'] = array (
			'#type' => 'hidden',
			'#value' => $node->vid,
			'#name' => 'hidden'
			);
	return $form;
}

function belead_product_add_form_validate($form, & $form_state)
{
}

function belead_product_add_form_submit_add($form, & $form_state)
{
	$name = $form_state['values']['belead_product_name'];
	$description = $form_state['values']['belead_product_description'];
	$cid = $form_state['values']['belead_product_hidden'];
	db_query("insert into belead_product_content (cid, name, description) values (%d, '%s', '%s')", $cid, $name, $description);
	$result = db_query("select id from belead_product_content where name = '%s'", $name);
	$row = db_fetch_array($result);
	$picture_name= $_FILES['files']['name']['belead_product_picture'];
	$node= $form {
		'#node' };
	$new_picture_name = 'product_' . $row['id'] . '_' . '.jpg';
	$tmp_name = $_FILES['files']['tmp_name']['belead_product_picture'];
	move_uploaded_file($tmp_name, "sites/default/files/belead_product/" . $new_picture_name);
	db_query("update belead_product_content set picture = '%s' where id = %d", $new_picture_name, $row['id']);
}

function belead_product_add_form_submit_cancel($form, & $form_state)
{
}

function belead_product_edit_form($form_state, $node)
{ 
	$product_id = intval($_GET['product_id']);
	$result = db_query('select * from belead_product_content where id = %d', $product_id);
	$row = db_fetch_array($result);
	$form = array ();
	$form['belead_product_edits'] = array (
			'#type' => 'fieldset',
			'#title' => t('Edit Product'),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE,
			'#prefix' => '<div class="belead_product_edit_form">',
			'#suffix' => '</div>',
			'#weight' => 30
			);
	$form['#node']= $node;
	$form['#attributes'] = array (
			'enctype' => "multipart/form-data"
			);
	$form['#validate'][] = 'belead_product_edit_form_validate';
	$form['belead_product_edits']['belead_product_category_name'] = array (
			'#type' => 'textfield',
			'#title' => t('Name'),
			'#default_value' => $row['name'],
			'#size' => 85
			);
	$form['belead_product_edits']['belead_product_picture'] = array (
			'#type' => 'file',
			'#title' => t('Picture'),
			'#size' => 40
			);
	$form['belead_product_edits']['belead_product_description'] = array (
			'#type' => 'textarea',
			'#resizable' => FALSE,
			'#title' => t('Description'),
			'#default_value' => $row['description'],
			'#size' => 255
			);
	$form['submitted'] = array (
			'#tree' => TRUE
			);
	$form['belead_product_edits']['belead_product_button_edit'] = array (
			'#type' => 'submit',
			'#value' => t('Update'),
			'#name' => 'update',
			'#submit' => array('belead_product_edit_form_submit_update')
			);
	$form['belead_product_edits']['belead_product_button_cancel'] = array (
			'#type' => 'submit',
			'#value' => t('Cancel'),
			'#name' => 'cancel',
			'#submit' => array('belead_product_edit_form_submit_cancel')
			);
	$form['belead_product_edits']['belead_product_hidden'] = array (
			'#type' => 'hidden',
			'#value' => $product_id,
			'#name' => 'hidden'
			);
	return $form;
}

function belead_product_edit_form_validate($form, & $form_state)
{
}

function belead_product_edit_form_submit_update($form, & $form_state)
{
	$name = $form_state['values']['belead_product_name'];
	$description = $form_state['values']['belead_product_description'];
	$id = $form_state['values']['belead_product_hidden'];
	$picture_name= $_FILES['files']['name']['belead_product_picture'];
	$node= $form {
		'#node' };
	$new_picture_name = 'product_' . $row['id'] . '_' . $picture_name;
	$tmp_name = $_FILES['files']['tmp_name']['belead_product_picture'];
	move_uploaded_file($tmp_name, "sites/default/files/" . $new_picture_name);
	db_query("update belead_product_content set name = '%s', picture = '%s', description = '%s' where id = %d", $name, $new_picture_name, $description, $row['id']);
}

function belead_product_edit_form_submit_cancel($form, & $form_state)
{
}

function belead_product_delete_form($node)
{
	$product_id = intval($_GET['product_id']);

	$form = array();
	$form['belead_product_deletes'] = array (
			'#type' => 'fieldset',
			'#title' => t('Delete Product'),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE,
			'#description' => t('Are you sure to delete this product information?'),
			'#prefix' => '<div class="belead_product_delete_form">',
			'#suffix' => '</div>',
			'#weight' => 30
			);
	$form['#node'] = $node;
	$form['#attributes'] = array (
			'enctype' => "multipart/form-data"
			);
	$form['#validate'][] = 'belead_product_delete_form_validate';
	$form['submitted'] = array (
			'#tree' => TRUE
			);
	$form['belead_product_deletes']['belead_product_button_delete'] = array (
			'#type' => 'submit',
			'#value' => t('Delete'),
			'#name' => 'delete',
			'#submit' => array('belead_product_delete_form_submit_delete')
			);
	$form['belead_product_deletes']['belead_product_button_cancel'] = array (
			'#type' => 'submit',
			'#value' => t('Cancel'),
			'#name' => 'cancel',
			'#submit' => array('belead_product_delete_form_submit_cancel')
			);
	$form['belead_product_deletes']['belead_product_hidden'] = array (
			'#type' => 'hidden',
			'#value' => $product_id,
			'#name' => 'hidden'
			);
	return $form;
}

/**
 * hook_validate implementation for delete form.
 */
function belead_product_delete_form_validate($form, & $form_state)
{
}

/**
 * hook_submit implementation for delete form.
 */
function belead_product_delete_form_submit_delete($form, & $form_state)
{
	$id = $form_state['values']['belead_product_hidden'];
	$sql = "delete from belead_product_content where id = $id";
	db_query($sql);
}

/**
 * hook_submit implementation for delete form.
 */
function belead_product_delete_form_submit_cancel($form, & $form_state)
{
}

/**
 * Implementation of hook_theme().
 *
 * This lets us tell Drupal about our theme functions and their arguments.
 */
function belead_product_theme()
{
	return array(
			'belead_product_main' => array (
				'arguments' => array ('node'),
				),
			'belead_product_category_main' => array (
				'arguments' => array ('node'),
				),
			'belead_product_script' => array (
				'arguments' => array ('node' => NULL),
				),
			'belead_product_page_title' => array (
				'arguments' => array ('node' => NULL),
				)
		     );
}

function theme_belead_product_page_title($node)
{
	return !empty ($node->title) ? $node->title : '';
}

function theme_belead_product_script(& $node)
{
	$output = '<script type="text/javascript" src="sites/all/libraries/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>';
	$output .= '<script type="text/javascript">tinyMCE.init({
			mode : "textareas",
		       	theme : "advanced",
		       	skin : "o2k7",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_resizing : true,
			theme_advanced_buttons1 : "cut, copy, paste, separator, undo, redo, separator, bold, italic, underline, strikethrough, separator, justifyleft, justifycenter, justifyright, justifyfull, separator, bullist, numlist, separator, formatselect, styleselect, fontselect, fontsizeselect",
			theme_advanced_buttons2 : "outdent, indent, separator, link, unlink, anchor, separator, image, hr, separator, sub, sup, separator, forecolor, backcolor, separator, charmap, visualaid, separator, blockquote, removeformat, cleanup, newdocument, code",
			theme_advanced_buttons3 : "",
		       	width : "704",
		       	height : "300"
			});</script>';

	$output .= '<style type="text/css">';
	$output .= '#edit-belead-page-body {color: 005858;}';
	$output .= '</style>';

	return $output;
}

function theme_belead_product_main($node)
{
	$product_id = intval($_GET['product_id']);
	$result = db_query('select * from belead_product_content where id = %d', $product_id);
	$row = db_fetch_array($result);
	$output = '<div class="belead_product_information">';
	$output .= '<img src="sites/default/files/belead_product/' . $row['picture'] . '"/>';
	$output .= '<table class="belead-table-auto-border">';
	$output .= '<tr>';
	$output .= '<td width="15%">';
	$output .= '<b>';
	$output .= t('Name');
	$output .= '</b>';
	$output .= '</td>';
	$output .= '<td>';
	$output .= $row['name'];
	$output .= '</td>';
	$output .= '</tr>';
	$output .= '<tr>';
	$output .= '<td width="15%">';
	$output .= '<b>';
	$output .= t('Description');
	$output .= '</b>';
	$output .= '</td>';
	$output .= '<td>';
	$output .= $row['description'];
	$output .= '</td>';
	$output .= '</tr>';
	$output .= '</table>';
	if (user_access(BELEAD_HIRE_MANAGE)) {
		$output .= '</p>';
		$output .= l(t('Edit'), "node/$node->nid", array ('query' => array ('product_id' => $product_id, 'action' => 'edit')));
		$output .= '&nbsp;&nbsp;&nbsp;&nbsp;';
		$output .= l(t('Delete'), "node/$node->nid", array ('query' => array ('product_id' => $product_id, 'action' => 'delete')));
		$output .= '</p>';
	}
	$output .= '</div>';
	return $output;
}

function theme_belead_product_category_main($node)
{
	$output = '<div class="belead_product_category_information">';
	$result = db_query('select * from belead_product where vid = %d', $node->vid);
	$row = db_fetch_array($result);
	$result1 = db_query("select * from belead_product_content where cid = %d order by id desc", $node->vid);
	$output .= '<center>';
	$output .= '<marquee scrollAmount=3 scrollDelay=3 direction=right>';
	$output .= '<table>';
	$output .= '<tr>';
	while ($row1 = db_fetch_array($result1)) {
		$output .= '<td>';
		$output .= l('<img src="sites/default/files/belead_product/' . $row1['picture'] . '" alt=""  width="180" height="120"/>', "node/$node->nid", array ('query' => array ('product_id' => $row1['id']), 'html' => TRUE));
		$output .= '</td>';
	}
	$output .= '</tr>';
	$output .= '</table>';
	$output .= '</marquee>';
	$output .= '</center>';
	$output .= '<table class="belead-table-auto-border">';
	$output .= '<tr>';
	$output .= '<td width="15%">';
	$output .= '<b>';
	$output .= t('Category Name');
	$output .= '</b>';
	$output .= '</td>';
	$output .= '<td>';
	$output .= $row['category_name'];
	$output .= '</td>';
	$output .= '</tr>';
	$output .= '<tr>';
	$output .= '<td width="15%">';
	$output .= '<b>';
	$output .= t('Application Area');
	$output .= '</b>';
	$output .= '</td>';
	$output .= '<td>';
	$output .= $row['application_area'];
	$output .= '</td>';
	$output .= '</tr>';
	$output .= '<tr>';
	$output .= '<td width="15%">';
	$output .= '<b>';
	$output .= t('Description');
	$output .= '</b>';
	$output .= '</td>';
	$output .= '<td>';
	$output .= $row['category_description'];
	$output .= '</td>';
	$output .= '</tr>';
	$output .= '</table>';
	$output .= '</div>';
	return $output;
}

function belead_product_match_path($path, $patterns)
{
	static $regexps;

	if (!isset ($regexps[$patterns])) {
		$regexps[$patterns]= '/^('.preg_replace(array (
						'/(\r\n?|\n)/',
						'/\\\\\*/'
						), array (
							'|',
							'.*'
							), preg_quote($patterns, '/')).')$/';
	}
	$result= preg_match($regexps[$patterns], $path) == 1;
	return $result;
}

/**
 * Callback for belead_product/%node menu.
 */
function _belead_product_callback($node)
{
	exit ();
}

/**
 * hook_menu implementation.
 */
function belead_product_menu()
{
	$items= array ();
	$items['belead_product/%node']= array (
			'page callback' => '_belead_product_callback',
			'page arguments' => array (
				1
				),
			'type' => MENU_CALLBACK,
			'access arguments' => array (
				'access content'
				)
			);
	return $items;
}
