<?php
// $Id: translation_table.module,v 1.1.2.2 2009/05/26 05:19:59 pasqualle Exp $

/**
 * @file
 * Translation table module
 *
 * UI for quick translation of taxonomies and menus.
 * The i18n module allows for translation of taxonomy terms and menu items, but
 * the process is tedious - you need to look up strings you want to translate,
 * there is no overview of what's already translated etc.
 *
 * This module presents your taxonomy terms or menu items in a table, and each
 * language has a corresponding column. Just fill out the translations and click
 * Save.
 *
 * @author Zoltan Varady, 2008
 */

/**
 * Implementation of hook_menu().
 */
function translation_table_menu() {
  $items['admin/build/translate/table'] = array(
    'title' => 'Translation table',
    'description' => 'Edit menu and taxonomy translations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('translation_table_taxonomy_form'),
    'access callback' => 'user_access',
    'access arguments' => array('translate interface'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/admin.inc',
  );

  $items['admin/build/translate/table/taxonomy'] = array(
    'title' => 'Taxonomy',
    'description' => 'Edit taxonomy translations',
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/build/translate/table/menu'] = array(
    'title' => 'Menu',
    'description' => 'Edit menu translations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('translation_table_menu_form'),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('translate interface'),
    'file' => 'includes/admin.inc',
  );

  $items['admin/build/translate/table/node-type'] = array(
    'title' => 'Content type',
    'description' => 'Edit content type translations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('translation_table_nodetype_form'),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('translate interface'),
    'file' => 'includes/admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function translation_table_theme() {
  return array(
    'translation_table' => array(
      'arguments' => array('form' => NULL),
      'file' => 'includes/admin.inc',
    ),
    'translation_table_taxonomy_filter' => array(
      'arguments' => array('form' => NULL),
      'file' => 'includes/admin.inc',
    ),
    'translation_table_menu_filter' => array(
      'arguments' => array('form' => NULL),
      'file' => 'includes/admin.inc',
    ),
    'translation_table_nodetype_filter' => array(
      'arguments' => array('form' => NULL),
      'file' => 'includes/admin.inc',
    ),
  );
}
