<?php
// $Id: belead_employee.module,v 1.26 2008/01/19 21:13:58 bdragon Exp $

/**
 * Implementation of hook_node_info(). This function replaces hook_node_name()
 * and hook_node_types() from 4.6. Drupal 5 expands this hook significantly.
 *
 * This is a required node hook. This function describes the nodes provided by
 * this module.
 *
 * The required attributes are:
 * - "name" provides a human readable name for the node,
 * - "module" tells Drupal how the module's functions map to hooks (i.e. if the
 *   module is belead_employee_foo then belead_employee_foo_insert will be called
 *   when inserting the node).
 * - "description" provides a brief description of the node type, which is
 *   show up when a user accesses the "Create content" page for that node type.
 *
 * The other optional, attributes:
 * - "has_title" boolean that indicates whether or not this node type has a
 *   title field.
 * - "title_label": the label for the title field of this content type.
 * - "has_body": boolean that indicates whether or not this node type has a
 *   body field.
 * - "body_label": the label for the body field of this content type.
 * - "min_word_count": the minimum number of words for the body field to be
 *   considered valid for this content type.
 */
define(BELEAD_EMPLOYEE_CREATE_CONTENT, 'create belead employee content');
define(BELEAD_EMPLOYEE_EDIT_ANY_CONTENT, 'edit any belead employee content');
define(BELEAD_EMPLOYEE_EDIT_OWN_CONTENT, 'edit own belead employee content');
define(BELEAD_EMPLOYEE_DELETE_ANY_CONTENT, 'delete any belead employee content');
define(BELEAD_EMPLOYEE_DELETE_OWN_CONTENT, 'delete own belead employee content');
define(BELEAD_EMPLOYEE_MANAGE, 'manage belead employee');

function belead_employee_node_info()
{
	return array (
			'belead_employee' => array(
				'name' => t('Belead Employee'),
				'module' => 'belead_employee',
				'description' => t("This is belead employee node type."),
				'has_title' => TRUE,
				'title_label' => t('Page Title'),
				'has_body' => TRUE,
				'body_label' => t('Page Body'),
				)
		    );
}

/**
 * Implementation of hook_access().
 *
 * Node modules may implement node_access() to determine the operations
 * users may perform on nodes. This example uses a very common access pattern.
 */
function belead_employee_access($op, $node, $account)
{
	if ($op == 'create') {
		return user_access(BELEAD_EMPLOYEE_CREATE_CONTENT, $account);
	}

	if ($op == 'update') {
		if (user_access(BELEAD_EMPLOYEE_EDIT_ANY_CONTENT, $account) || (user_access(BELEAD_EMPLOYEE_EDIT_OWN_CONTENT, $account) && ($account->uid == $node->uid))) {
			return TRUE;
		}
	}

	if ($op == 'delete') {
		if (user_access(BELEAD_EMPLOYEE_DELETE_ANY_CONTENT, $account) || (user_access(BELEAD_EMPLOYEE_DELETE_OWN_CONTENT, $account) && ($account->uid == $node->uid))) {
			return TRUE;
		}
	}
}

/**
 * Implementation of hook_perm().
 *
 * Since we are limiting the ability to create new nodes to certain users,
 * we need to define what those permissions are here. We also define a permission
 * to allow users to edit the nodes they created.
 */
function belead_employee_perm()
{
	return array(
			BELEAD_EMPLOYEE_CREATE_CONTENT,
			BELEAD_EMPLOYEE_EDIT_ANY_CONTENT,
			BELEAD_EMPLOYEE_EDIT_OWN_CONTENT,
			BELEAD_EMPLOYEE_DELETE_ANY_CONTENT,
			BELEAD_EMPLOYEE_DELETE_OWN_CONTENT,
			BELEAD_EMPLOYEE_MANAGE,
		    );
}

/**
 * Implementation of hook_form().
 *
 * Now it's time to describe the form for collecting the information
 * specific to this node type. This hook requires us to return an array with
 * a sub array containing information for each element in the form.
 */
function belead_employee_form(&$node)
{
	// The site admin can decide if this node type has a title and body, and how
	// the fields should be labeled. We need to load these settings so we can
	// build the node form correctly.
	$type = node_get_types('type', $node);

	if ($type->has_title) {
		$form['title'] = array(
				'#type' => 'textfield',
				'#title' => check_plain($type->title_label),
				'#required' => TRUE,
				'#default_value' => $node->title,
				'#weight' => -5
				);
	}

	if ($type->has_body) {
		// In Drupal 6, we can use node_body_field() to get the body and filter
		// elements. This replaces the old textarea + filter_form() method of
		// setting this up. It will also ensure the teaser splitter gets set up
		// properly.
		$form['body_field'] = node_body_field($node, $type->body_label, $type->min_word_count);
	}
	$form['page_type'] = array(
			'#type' => 'textfield',
			'#title' => t('Usage'),
			'#default_value' => isset($node->page_type) ? $node->page_type : '',
			'#size' => 20,
			'#maxlength' => 20
			);

	return $form;
}

/**
 * Implementation of hook_validate().
 *
 * Our "quantity" field requires a number to be entered. This hook lets
 * us ensure that the user entered an appropriate value before we try
 * inserting anything into the database.
 *
 * Errors should be signaled with form_set_error().
 */
function belead_employee_validate(&$node)
{
}

/**
 * Implementation of hook_insert().
 *
 * As a new node is being inserted into the database, we need to do our own
 * database inserts.
 */
function belead_employee_insert($node)
{
	db_query("INSERT INTO {belead_employee} (vid, nid) VALUES (%d, %d, '%s')", $node->vid, $node->nid, $node->page_type);
}

/**
 * Implementation of hook_update().
 *
 * As an existing node is being updated in the database, we need to do our own
 * database updates.
 */
function belead_employee_update($node)
{
	// if this is a new node or we're adding a new revision,
	if ($node->revision) {
		belead_employee_insert($node);
	} else {
		db_query("update belead_employee set page_type = '%s' where vid = %d", $node->page_type, $node->vid);
	}
}

/**
 * Implementation of hook_nodeapi().
 *
 * When a node revision is deleted, we need to remove the corresponding record
 * from our table. The only way to handle revision deletion is by implementing
 * hook_nodeapi().
 */
function belead_employee_nodeapi(&$node, $op, $teaser, $page)
{
	switch ($op) {
		case 'delete revision':
			// Notice that we're matching a single revision based on the node's vid.
			db_query('DELETE FROM {belead_employee} WHERE vid = %d', $node->vid);
			break;
	}
}

/**
 * Implementation of hook_delete().
 *
 * When a node is deleted, we need to remove all related records from out table.
 */
function belead_employee_delete($node)
{
	// Notice that we're matching all revision, by using the node's nid.
	db_query('DELETE FROM {belead_employee} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 *
 * Now that we've defined how to manage the node data in the database, we
 * need to tell Drupal how to get the node back out. This hook is called
 * every time a node is loaded, and allows us to do some loading of our own.
 */
function belead_employee_load($node)
{
	$additions = db_fetch_object(db_query('SELECT * FROM {belead_employee} WHERE vid = %d', $node->vid));
	return $additions;
}

/**
 * Implementation of hook_view().
 *
 * This is a typical implementation that simply runs the node text through
 * the output filters.
 */
function belead_employee_view($node, $teaser = FALSE, $page = FALSE)
{
	global $user, $base_url;
	$node = node_prepare($node, $teaser);

	/* Full node content view */
	$result = db_query("select * from belead_employee where vid = $node->vid");
	$row = db_fetch_array($result);
	$page_type = $row['page_type'];
	drupal_set_title(theme('belead_employee_page_title', $node));
	switch ($page_type) {
		case normal:
			$node->content['belead_employee_main'] = array (
					'#value' => theme('belead_employee_main', $node),
					'#weight' => 1
					);
			if (user_access(BELEAD_EMPLOYEE_MANAGE)) {
				$node->content['belead_employee_script'] = array (
						'#value' => theme('belead_employee_script', $node),
						'#weight' => 2
						);
				$form = drupal_get_form('belead_employee_edit_form', $node);
				$node->content['belead_employee_edit'] = array (
						'#value' => $form,
						'#weight' => 2
						);
			}
			break;
		case information:
			$node->content['belead_employee_information'] = array (
					'#value' => theme('belead_employee_information', $node),
					'#weight' => 1
					);
			if (user_access(BELEAD_EMPLOYEE_MANAGE)) {
				$node->content['belead_employee_script'] = array (
						'#value' => theme('belead_employee_script', $node),
						'#weight' => 2
						);
				$form = drupal_get_form('belead_employee_information_edit_form', $node);
				$node->content['belead_employee_information_edit'] = array (
						'#value' => $form,
						'#weight' => 2
						);
			}
			break;
		case manual:
			break;
		case goal:
			break;
		case program:
			break;
		default:
			break;
	}
	return $node;
}

function belead_employee_edit_form($form_state, $node)
{ 
	$form = array ();
	$form['belead_employee_edits'] = array (
			'#type' => 'fieldset',
			'#title' => t('Edit Page'),
			'#collapsible' => TRUE,
			'#collapsed' => TRUE,
			'#prefix' => '<div class="belead_employee_edit_form">',
			'#suffix' => '</div>',
			'#weight' => 30
			);
	$form['#node']= $node;
	$form['#attributes'] = array (
			'enctype' => "multipart/form-data"
			);
	$form['#validate'][] = 'belead_employee_edit_form_validate';
	$form['belead_employee_edits']['belead_employee_title'] = array (
			'#type' => 'textfield',
			'#title' => t('Title'),
			'#default_value' => $node->title,
			'#size' => 85
			);
	$form['belead_employee_edits']['belead_employee_body'] = array (
			'#type' => 'textarea',
			'#resizable' => FALSE,
			'#title' => t('Body'),
			'#default_value' => $node->body,
			'#size' => 255
			);
	$form['submitted'] = array (
			'#tree' => TRUE
			);
	$form['belead_employee_edits']['belead_employee_button_edit'] = array (
			'#type' => 'submit',
			'#value' => t('Update'),
			'#name' => 'update',
			'#submit' => array('belead_employee_edit_form_submit_update')
			);
	$form['belead_employee_edits']['belead_employee_button_cancel'] = array (
			'#type' => 'submit',
			'#value' => t('Cancel'),
			'#name' => 'cancel',
			'#submit' => array('belead_employee_edit_form_submit_cancel')
			);
	$form['belead_employee_edits']['belead_employee_hidden'] = array (
			'#type' => 'hidden',
			'#value' => $node->nid,
			'#name' => 'hidden'
			);
	return $form;
}

function belead_employee_edit_form_validate($form, & $form_state)
{
}

function belead_employee_edit_form_submit_update($form, & $form_state)
{
	$title = $form_state['values']['belead_employee_title'];
	$body = $form_state['values']['belead_employee_body'];
	$nid = $form_state['values']['belead_employee_hidden'];
	db_query("update node_revisions set title = '%s', body = '%s' where vid = %d", $title, $body, $nid);
}

function belead_employee_edit_form_submit_cancel($form, & $form_state)
{
}

/**
 * Implementation of hook_theme().
 *
 * This lets us tell Drupal about our theme functions and their arguments.
 */
function belead_employee_theme()
{
	return array(
			'belead_employee_main' => array (
				'arguments' => array ('node'),
				),
			'belead_employee_script' => array (
				'arguments' => array ('node' => NULL),
				),
			'belead_employee_page_title' => array (
				'arguments' => array ('node' => NULL),
				)
		     );
}

function theme_belead_employee_page_title($node)
{
	return !empty ($node->title) ? $node->title : '';
}

function theme_belead_employee_script(& $node)
{
	$output = '<script type="text/javascript" src="sites/all/libraries/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>';
	$output .= '<script type="text/javascript">tinyMCE.init({
			mode : "textareas",
		       	theme : "advanced",
		       	skin : "o2k7",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_resizing : true,
			theme_advanced_buttons1 : "cut, copy, paste, separator, undo, redo, separator, bold, italic, underline, strikethrough, separator, justifyleft, justifycenter, justifyright, justifyfull, separator, bullist, numlist, separator, formatselect, styleselect, fontselect, fontsizeselect",
			theme_advanced_buttons2 : "outdent, indent, separator, link, unlink, anchor, separator, image, hr, separator, sub, sup, separator, forecolor, backcolor, separator, charmap, visualaid, separator, blockquote, removeformat, cleanup, newdocument, code",
			theme_advanced_buttons3 : "",
		       	width : "704",
		       	height : "300"
			});</script>';

	$output .= '<style type="text/css">';
	$output .= '#edit-belead-page-body {color: 005858;}';
	$output .= '</style>';

	return $output;
}

function theme_belead_employee_main($node)
{
	$output = '';
	return $output;
}

function belead_employee_match_path($path, $patterns)
{
	static $regexps;

	if (!isset ($regexps[$patterns])) {
		$regexps[$patterns]= '/^('.preg_replace(array (
						'/(\r\n?|\n)/',
						'/\\\\\*/'
						), array (
							'|',
							'.*'
							), preg_quote($patterns, '/')).')$/';
	}
	$result= preg_match($regexps[$patterns], $path) == 1;
	return $result;
}

/**
 * Callback for belead_employee/%node menu.
 */
function _belead_employee_callback($node)
{
	exit ();
}

/**
 * hook_menu implementation.
 */
function belead_employee_menu()
{
	$items= array ();
	$items['belead_employee/%node']= array (
			'page callback' => '_belead_employee_callback',
			'page arguments' => array (
				1
				),
			'type' => MENU_CALLBACK,
			'access arguments' => array (
				'access content'
				)
			);
	return $items;
}
