<?php
// $Id: luopin_manu.module,v 1.26 2008/01/19 21:13:58 bdragon Exp $

/**
 * Implementation of hook_node_info(). This function replaces hook_node_name()
 * and hook_node_types() from 4.6. Drupal 5 expands this hook significantly.
 *
 * This is a required node hook. This function describes the nodes provided by
 * this module.
 *
 * The required attributes are:
 * - "name" provides a human readable name for the node,
 * - "module" tells Drupal how the module's functions map to hooks (i.e. if the
 *   module is luopin_manu_foo then luopin_manu_foo_insert will be called
 *   when inserting the node).
 * - "description" provides a brief description of the node type, which is
 *   show up when a user accesses the "Create content" page for that node type.
 *
 * The other optional, attributes:
 * - "has_title" boolean that indicates whether or not this node type has a
 *   title field.
 * - "title_label": the label for the title field of this content type.
 * - "has_body": boolean that indicates whether or not this node type has a
 *   body field.
 * - "body_label": the label for the body field of this content type.
 * - "min_word_count": the minimum number of words for the body field to be
 *   considered valid for this content type.
 */
define(LUOPIN_MANU_CREATE_CONTENT, 'create luopin manu content');
define(LUOPIN_MANU_EDIT_ANY_CONTENT, 'edit any luopin manu content');
define(LUOPIN_MANU_EDIT_OWN_CONTENT, 'edit own luopin manu content');
define(LUOPIN_MANU_DELETE_ANY_CONTENT, 'delete any luopin manu content');
define(LUOPIN_MANU_DELETE_OWN_CONTENT, 'delete own luopin manu content');
define(LUOPIN_MANU_MANAGE, 'manage luopin manu');

function luopin_manu_node_info()
{
	return array (
			'luopin_manu' => array(
				'name' => t('Luopin Manu'),
				'module' => 'luopin_manu',
				'description' => t("This is luopin manu node type."),
				'has_title' => TRUE,
				'title_label' => t('Page Title'),
				'has_body' => TRUE,
				'body_label' => t('Page Body'),
				)
		    );
}

/**
 * Implementation of hook_access().
 *
 * Node modules may implement node_access() to determine the operations
 * users may perform on nodes. This example uses a very common access pattern.
 */
function luopin_manu_access($op, $node, $account)
{
	if ($op == 'create') {
		return user_access(LUOPIN_MANU_CREATE_CONTENT, $account);
	}

	if ($op == 'update') {
		if (user_access(LUOPIN_MANU_EDIT_ANY_CONTENT, $account) || (user_access(LUOPIN_MANU_EDIT_OWN_CONTENT, $account) && ($account->uid == $node->uid))) {
			return TRUE;
		}
	}

	if ($op == 'delete') {
		if (user_access(LUOPIN_MANU_DELETE_ANY_CONTENT, $account) || (user_access(LUOPIN_MANU_DELETE_OWN_CONTENT, $account) && ($account->uid == $node->uid))) {
			return TRUE;
		}
	}
}

/**
 * Implementation of hook_perm().
 *
 * Since we are limiting the ability to create new nodes to certain users,
 * we need to define what those permissions are here. We also define a permission
 * to allow users to edit the nodes they created.
 */
function luopin_manu_perm()
{
	return array(
			LUOPIN_MANU_CREATE_CONTENT,
			LUOPIN_MANU_EDIT_ANY_CONTENT,
			LUOPIN_MANU_EDIT_OWN_CONTENT,
			LUOPIN_MANU_DELETE_ANY_CONTENT,
			LUOPIN_MANU_DELETE_OWN_CONTENT,
			LUOPIN_MANU_MANAGE,
		    );
}

/**
 * Implementation of hook_form().
 *
 * Now it's time to describe the form for collecting the information
 * specific to this node type. This hook requires us to return an array with
 * a sub array containing information for each element in the form.
 */
function luopin_manu_form(&$node)
{
	// The site admin can decide if this node type has a title and body, and how
	// the fields should be labeled. We need to load these settings so we can
	// build the node form correctly.
	$type = node_get_types('type', $node);

	if ($type->has_title) {
		$form['title'] = array(
				'#type' => 'textfield',
				'#title' => check_plain($type->title_label),
				'#required' => TRUE,
				'#default_value' => $node->title,
				'#weight' => -5
				);
	}

	if ($type->has_body) {
		// In Drupal 6, we can use node_body_field() to get the body and filter
		// elements. This replaces the old textarea + filter_form() method of
		// setting this up. It will also ensure the teaser splitter gets set up
		// properly.
		$form['body_field'] = node_body_field($node, $type->body_label, $type->min_word_count);
	}

	$form['category'] = array(
			'#type' => 'textfield',
			'#title' => t('Category'),
			'#default_value' => isset($node->category) ? $node->category : '',
			'#size' => 80,
			'#maxlength' => 80
			);

	return $form;
}

/**
 * Implementation of hook_validate().
 *
 * Our "quantity" field requires a number to be entered. This hook lets
 * us ensure that the user entered an appropriate value before we try
 * inserting anything into the database.
 *
 * Errors should be signaled with form_set_error().
 */
function luopin_manu_validate(&$node)
{
}

/**
 * Implementation of hook_insert().
 *
 * As a new node is being inserted into the database, we need to do our own
 * database inserts.
 */
function luopin_manu_insert($node)
{
	db_query("INSERT INTO {luopin_manu} (vid, nid, category) VALUES (%d, %d, '%s')", $node->vid, $node->nid, $node->category);
}

/**
 * Implementation of hook_update().
 *
 * As an existing node is being updated in the database, we need to do our own
 * database updates.
 */
function luopin_manu_update($node)
{
	// if this is a new node or we're adding a new revision,
	if ($node->revision) {
		luopin_manu_insert($node);
	} else {
		db_query("UPDATE {luopin_manu} SET category = '%s' WHERE vid = %d", $node->category, $node->vid);
	}
}

/**
 * Implementation of hook_nodeapi().
 *
 * When a node revision is deleted, we need to remove the corresponding record
 * from our table. The only way to handle revision deletion is by implementing
 * hook_nodeapi().
 */
function luopin_manu_nodeapi(&$node, $op, $teaser, $page)
{
	switch ($op) {
		case 'delete revision':
			// Notice that we're matching a single revision based on the node's vid.
			db_query('DELETE FROM {luopin_manu} WHERE vid = %d', $node->vid);
			break;
	}
}

/**
 * Implementation of hook_delete().
 *
 * When a node is deleted, we need to remove all related records from out table.
 */
function luopin_manu_delete($node)
{
	// Notice that we're matching all revision, by using the node's nid.
	db_query('DELETE FROM {luopin_manu} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 *
 * Now that we've defined how to manage the node data in the database, we
 * need to tell Drupal how to get the node back out. This hook is called
 * every time a node is loaded, and allows us to do some loading of our own.
 */
function luopin_manu_load($node)
{
	$additions = db_fetch_object(db_query('SELECT * FROM {luopin_manu} WHERE vid = %d', $node->vid));
	return $additions;
}

/**
 * Implementation of hook_view().
 *
 * This is a typical implementation that simply runs the node text through
 * the output filters.
 */
function luopin_manu_view($node, $teaser = FALSE, $page = FALSE)
{
	global $user, $base_url;
	$node = node_prepare($node, $teaser);

	/* Full node content view */
	drupal_set_title(theme('luopin_manu_page_title', $node));
	if (user_access(LUOPIN_MANU_MANAGE)) {
		$node->content['luopin_manu_script'] = array (
				'#value' => theme('luopin_manu_script', $node),
				'#weight' => 1
				);
	}
	$result = db_query('select * from luopin_manu where vid = %d', $node->vid);
	$row = db_fetch_array($result);
	if (isset($_GET['manu_id'])) {
		if ($_GET['action'] == 'edit') {
			$form = drupal_get_form('luopin_manu_edit_form', $node);
			$node->content['luopin_manu_edit'] = array (
					'#value' => $form,
					'#weight' => 2
					);
		} elseif ($_GET['action'] == 'delete') {
			$form = drupal_get_form('luopin_manu_delete_form', $node);
			$node->content['luopin_manu_delete'] = array (
					'#value' => $form,
					'#weight' => 2
					);
		} else {
			$node->content['luopin_manu_main'] = array (
					'#value' => theme('luopin_manu_main', $node),
					'#weight' => 2
					);
		}
	} else {
		if ($row['category'] == 'equipments' || $row['category'] == 'products') {
			$node->content['luopin_manu_category_main'] = array (
					'#value' => theme('luopin_manu_category_main', $node),
					'#weight' => 2
					);
		} else {
			$node->content['luopin_manu_main'] = array (
					'#value' => theme('luopin_manu_main', $node),
					'#weight' => 2
					);
			if (user_access(LUOPIN_MANU_MANAGE)) {
				$form = drupal_get_form('luopin_manu_add_form', $node);
				$node->content['luopin_manu_add'] = array (
						'#value' => $form,
						'#weight' => 3
						);
			}
		}
	}
	return $node;
}

function luopin_manu_add_form($form_state, $node)
{ 
	$form = array ();
	$form['luopin_manu_adds'] = array (
			'#type' => 'fieldset',
			'#title' => t('Add Item'),
			'#collapsible' => TRUE,
			'#collapsed' => TRUE,
			'#prefix' => '<div class="luopin_manu_add_form">',
			'#suffix' => '</div>',
			'#weight' => 30
			);
	$form['#node']= $node;
	$form['#attributes'] = array (
			'enctype' => "multipart/form-data"
			);
	$form['#validate'][] = 'luopin_manu_add_form_validate';
	$form['luopin_manu_adds']['luopin_manu_name'] = array (
			'#type' => 'textfield',
			'#title' => t('Name'),
			'#size' => 85
			);
	$form['luopin_manu_adds']['luopin_manu_picture'] = array (
			'#type' => 'file',
			'#title' => t('Picture'),
			'#size' => 40
			);
	$form['luopin_manu_adds']['luopin_manu_description'] = array (
			'#type' => 'textarea',
			'#resizable' => FALSE,
			'#title' => t('Description'),
			'#size' => 255
			);
	$form['submitted'] = array (
			'#tree' => TRUE
			);
	$form['luopin_manu_adds']['luopin_manu_button_add'] = array (
			'#type' => 'submit',
			'#value' => t('Add'),
			'#name' => 'add',
			'#submit' => array('luopin_manu_add_form_submit_add')
			);
	$form['luopin_manu_adds']['luopin_manu_button_cancel'] = array (
			'#type' => 'submit',
			'#value' => t('Cancel'),
			'#name' => 'cancel',
			'#submit' => array('luopin_manu_add_form_submit_cancel')
			);
	$form['luopin_manu_adds']['luopin_manu_hidden'] = array (
			'#type' => 'hidden',
			'#value' => $node->vid,
			'#name' => 'hidden'
			);
	return $form;
}

function luopin_manu_add_form_validate($form, & $form_state)
{
}

function luopin_manu_add_form_submit_add($form, & $form_state)
{
	$name = $form_state['values']['luopin_manu_name'];
	$description = $form_state['values']['luopin_manu_description'];
	$cid = $form_state['values']['luopin_manu_hidden'];
	$result = db_query('select category from luopin_manu where vid = %d', $cid);
	$row = db_fetch_array($result);
	$category = $row['category'];
	db_query("insert into luopin_manu_content (nid, category, name, description, language) values (%d, '%s', '%s', '%s', '%s')", $cid, $category, $name, $description, i18n_get_lang());
	$result = db_query("select id from luopin_manu_content where name = '%s'", $name);
	$row = db_fetch_array($result);
	$picture_name= $_FILES['files']['name']['luopin_manu_picture'];
	$node= $form {
		'#node' };
	$new_picture_name = 'manu_' . $row['id'] . '.png';
	$tmp_name = $_FILES['files']['tmp_name']['luopin_manu_picture'];
	move_uploaded_file($tmp_name, "sites/default/files/luopin_manu/" . $new_picture_name);
	db_query("update luopin_manu_content set picture = '%s' where id = %d", $new_picture_name, $row['id']);
}

function luopin_manu_add_form_submit_cancel($form, & $form_state)
{
}

function luopin_manu_edit_form($form_state, $node)
{ 
	$manu_id = intval($_GET['manu_id']);
	$result = db_query('select * from luopin_manu_content where id = %d', $manu_id);
	$row = db_fetch_array($result);
	$form = array ();
	$form['luopin_manu_edits'] = array (
			'#type' => 'fieldset',
			'#title' => t('Edit Item'),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE,
			'#prefix' => '<div class="luopin_manu_edit_form">',
			'#suffix' => '</div>',
			'#weight' => 30
			);
	$form['#node']= $node;
	$form['#attributes'] = array (
			'enctype' => "multipart/form-data"
			);
	$form['#validate'][] = 'luopin_manu_edit_form_validate';
	$form['luopin_manu_edits']['luopin_manu_name'] = array (
			'#type' => 'textfield',
			'#title' => t('Name'),
			'#default_value' => $row['name'],
			'#size' => 85
			);
	$form['luopin_manu_edits']['luopin_manu_picture'] = array (
			'#type' => 'file',
			'#title' => t('Picture'),
			'#size' => 40
			);
	$form['luopin_manu_edits']['luopin_manu_description'] = array (
			'#type' => 'textarea',
			'#resizable' => FALSE,
			'#title' => t('Description'),
			'#default_value' => $row['description'],
			'#size' => 255
			);
	$form['submitted'] = array (
			'#tree' => TRUE
			);
	$form['luopin_manu_edits']['luopin_manu_button_edit'] = array (
			'#type' => 'submit',
			'#value' => t('Update'),
			'#name' => 'update',
			'#submit' => array('luopin_manu_edit_form_submit_update')
			);
	$form['luopin_manu_edits']['luopin_manu_button_cancel'] = array (
			'#type' => 'submit',
			'#value' => t('Cancel'),
			'#name' => 'cancel',
			'#submit' => array('luopin_manu_edit_form_submit_cancel')
			);
	$form['luopin_manu_edits']['luopin_manu_hidden'] = array (
			'#type' => 'hidden',
			'#value' => $manu_id,
			'#name' => 'hidden'
			);
	return $form;
}

function luopin_manu_edit_form_validate($form, & $form_state)
{
}

function luopin_manu_edit_form_submit_update($form, & $form_state)
{
	$name = $form_state['values']['luopin_manu_name'];
	$description = $form_state['values']['luopin_manu_description'];
	$id = $form_state['values']['luopin_manu_hidden'];
	$picture_name= $_FILES['files']['name']['luopin_manu_picture'];
	if ($picture_name != '') {
		$new_picture_name = 'manu_' . $id . '.png';
		$tmp_name = $_FILES['files']['tmp_name']['luopin_manu_picture'];
		move_uploaded_file($tmp_name, "sites/default/files/luopin_manu" . $new_picture_name);
	}
	if ($picture_name != '') {
		db_query("update luopin_manu_content set name = '%s', picture = '%s', description = '%s' where id = %d", $name, $new_picture_name, $description, $id);
	} else {
		db_query("update luopin_manu_content set name = '%s', description = '%s' where id = %d", $name, $description, $id);
	}
}

function luopin_manu_edit_form_submit_cancel($form, & $form_state)
{
}

function luopin_manu_delete_form($node)
{
	$manu_id = intval($_GET['manu_id']);

	$form = array();
	$form['luopin_manu_deletes'] = array (
			'#type' => 'fieldset',
			'#title' => t('Delete Item'),
			'#collapsible' => TRUE,
			'#collapsed' => FALSE,
			'#description' => t('Are you sure to delete this manu information?'),
			'#prefix' => '<div class="luopin_manu_delete_form">',
			'#suffix' => '</div>',
			'#weight' => 30
			);
	$form['#node'] = $node;
	$form['#attributes'] = array (
			'enctype' => "multipart/form-data"
			);
	$form['#validate'][] = 'luopin_manu_delete_form_validate';
	$form['submitted'] = array (
			'#tree' => TRUE
			);
	$form['luopin_manu_deletes']['luopin_manu_button_delete'] = array (
			'#type' => 'submit',
			'#value' => t('Delete'),
			'#name' => 'delete',
			'#submit' => array('luopin_manu_delete_form_submit_delete')
			);
	$form['luopin_manu_deletes']['luopin_manu_button_cancel'] = array (
			'#type' => 'submit',
			'#value' => t('Cancel'),
			'#name' => 'cancel',
			'#submit' => array('luopin_manu_delete_form_submit_cancel')
			);
	$form['luopin_manu_deletes']['luopin_manu_hidden'] = array (
			'#type' => 'hidden',
			'#value' => $manu_id,
			'#name' => 'hidden'
			);
	return $form;
}

/**
 * hook_validate implementation for delete form.
 */
function luopin_manu_delete_form_validate($form, & $form_state)
{
}

/**
 * hook_submit implementation for delete form.
 */
function luopin_manu_delete_form_submit_delete($form, & $form_state)
{
	$id = $form_state['values']['luopin_manu_hidden'];
	$sql = "delete from luopin_manu_content where id = $id";
	db_query($sql);
}

/**
 * hook_submit implementation for delete form.
 */
function luopin_manu_delete_form_submit_cancel($form, & $form_state)
{
}

/**
 * Implementation of hook_theme().
 *
 * This lets us tell Drupal about our theme functions and their arguments.
 */
function luopin_manu_theme()
{
	return array(
			'luopin_manu_main' => array (
				'arguments' => array ('node'),
				),
			'luopin_manu_category_main' => array (
				'arguments' => array ('node'),
				),
			'luopin_manu_script' => array (
				'arguments' => array ('node' => NULL),
				),
			'luopin_manu_page_title' => array (
				'arguments' => array ('node' => NULL),
				)
		     );
}

function theme_luopin_manu_page_title($node)
{
	return !empty ($node->title) ? $node->title : '';
}

function theme_luopin_manu_script(& $node)
{
	$output = '<script type="text/javascript" src="sites/all/libraries/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>';
	$output .= '<script type="text/javascript">tinyMCE.init({
			mode : "textareas",
		       	theme : "advanced",
		       	skin : "o2k7",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_resizing : true,
			theme_advanced_buttons1 : "cut, copy, paste, separator, undo, redo, separator, bold, italic, underline, strikethrough, separator, justifyleft, justifycenter, justifyright, justifyfull, separator, bullist, numlist, separator, formatselect, fontselect, fontsizeselect",
			theme_advanced_buttons2 : "outdent, indent, separator, link, unlink, anchor, separator, image, hr, separator, sub, sup, separator, forecolor, backcolor, separator, charmap, visualaid, separator, blockquote, removeformat, cleanup, newdocument, code",
			theme_advanced_buttons3 : "",
		       	width : "500",
		       	height : "300"
			});</script>';

	return $output;
}

function theme_luopin_manu_main($node)
{
	$category_result = db_query('select * from luopin_manu where vid = %d', $node->vid);
	$category_row = db_fetch_array($category_result);
	$result = db_query("select * from luopin_manu_content where category = '%s' and language = '%s'", $category_row['category'], i18n_get_lang());
	$output = '<div class="luopin_manu_information">';
	while ($row = db_fetch_array($result)) {
		$output .= '<ul>';
		$output .= '<li>';
		$output .= '<a href="#' . $row['id'] . '">' . $row['name'] . '</a>'; 
		$output .= '</li>';
		$output .= '</ul>';
	}
	$result = db_query("select * from luopin_manu_content where category = '%s' and language = '%s'", $category_row['category'], i18n_get_lang());
	while ($row = db_fetch_array($result)) {
		$output .= '<p><a name="' . $row['id'] . '"/></p>';
		$output .= '<table class="luopin-manu-table">';
		$output .= '<tr>';
		$output .= '<th width="30%">';
		$output .= t('Name');
		$output .= '</th>';
		$output .= '<td rowspan="4">';
		$output .= '<img width="450" src="sites/default/files/luopin_manu/' . $row['picture'] . '"/>';
		$output .= '</td>';
		$output .= '</tr>';
		$output .= '<tr>';
		$output .= '<td class="name">';
		$output .= $row['name'];
		$output .= '</td>';
		$output .= '</tr>';
		$output .= '<tr>';
		$output .= '<th>';
		$output .= t('Description');
		$output .= '</th>';
		$output .= '</tr>';
		$output .= '<tr>';
		$output .= '<td>';
		$output .= $row['description'];
		$output .= '</td>';
		$output .= '</tr>';
		$output .= '</table>';
		if (user_access(BELEAD_HIRE_MANAGE)) {
			$output .= l(t('Edit'), "node/$node->nid", array ('query' => array ('manu_id' => $row['id'], 'action' => 'edit')));
			$output .= '&nbsp;&nbsp;&nbsp;&nbsp;';
			$output .= l(t('Delete'), "node/$node->nid", array ('query' => array ('manu_id' => $row['id'], 'action' => 'delete')));
		}
		$output .= '<div align="right"><a href="#">' . t('Return To Top') . '</a></div>';
	}
	$output .= '</div>';
	return $output;
}

function theme_luopin_manu_category_main($node)
{
	$output = '<div class="luopin_manu_category_information">';
	$result = db_query('select * from luopin_manu where vid = %d', $node->vid);
	$row = db_fetch_array($result);
	if ($row['category'] == 'equipments') {
		$output .= l(t('Sheet-metal Processing Equipments'), 'equipments/sheet');
		$result1 = db_query("select * from luopin_manu_content where category = 'panel_equipments' and language = '%s' order by id desc", i18n_get_lang());
		$output .= '<center>';
		$output .= '<marquee scrollAmount=3 scrollDelay=3 direction=right>';
		$output .= '<table class="luopin-manu-category-table">';
		$output .= '<tr>';
		while ($row1 = db_fetch_array($result1)) {
			$output .= '<td>';
			if (i18n_get_lang() == 'en') {
				$output .= '<a href="?q=equipments/sheet#' . $row1['id']. '">';
			} else {
				$output .= '<a href="?q=' . i18n_get_lang(). '/equipments/sheet#' . $row1['id']. '">';
			}
			$output .= '<img src="sites/default/files/luopin_manu/' . $row1['picture'] . '" alt=""  width="180" height="120"/>';
			$output .= '</a>';
			$output .= '</td>';
		}
		$output .= '</tr>';
		$output .= '</table>';
		$output .= '</marquee>';
		$output .= '</center>';
		$output .= l(t('Machine Tooling Equipments'), 'equipments/machine');
		$result1 = db_query("select * from luopin_manu_content where category = 'machine_equipments' and language = '%s' order by id desc", i18n_get_lang());
		$output .= '<center>';
		$output .= '<marquee scrollAmount=3 scrollDelay=3 direction=right>';
		$output .= '<table class="luopin-manu-category-table">';
		$output .= '<tr>';
		while ($row1 = db_fetch_array($result1)) {
			$output .= '<td>';
			if (i18n_get_lang() == 'en') {
				$output .= '<a href="?q=equipments/machine#' . $row1['id']. '">';
			} else {
				$output .= '<a href="?q=' . i18n_get_lang(). '/equipments/machine#' . $row1['id']. '">';
			}
			$output .= '<img src="sites/default/files/luopin_manu/' . $row1['picture'] . '" alt=""  width="180" height="120"/>';
			$output .= '</a>';
			$output .= '</td>';
		}
		$output .= '</tr>';
		$output .= '</table>';
		$output .= '</marquee>';
		$output .= '</center>';
	} else if ($row['category'] == 'products') {
		$output .= l(t('Sheet-metal Processing Products'), 'products/sheet');
		$result1 = db_query("select * from luopin_manu_content where category = 'panel_products' and language = '%s' order by id desc", i18n_get_lang());
		$output .= '<center>';
		$output .= '<marquee scrollAmount=3 scrollDelay=3 direction=right>';
		$output .= '<table class="luopin-manu-category-table">';
		$output .= '<tr>';
		while ($row1 = db_fetch_array($result1)) {
			$output .= '<td>';
			if (i18n_get_lang() == 'en') {
				$output .= '<a href="?q=products/sheet#' . $row1['id']. '">';
			} else {
				$output .= '<a href="?q=' . i18n_get_lang(). '/products/sheet#' . $row1['id']. '">';
			}
			$output .= '<img src="sites/default/files/luopin_manu/' . $row1['picture'] . '" alt=""  width="180" height="120"/>';
			$output .= '</a>';
			//$output .= l('<img src="sites/default/files/luopin_manu/' . $row1['picture'] . '" alt=""  width="180" height="120"/>', 'products/panel'. $row['id'], array('attributes' => array('a' => 'b', 'c' => 'd'), 'html' => TRUE));
			$output .= '</td>';
		}
		$output .= '</tr>';
		$output .= '</table>';
		$output .= '</marquee>';
		$output .= '</center>';
		$output .= l(t('Machine Tooling Products'), 'products/machine');
		$result1 = db_query("select * from luopin_manu_content where category = 'machine_products' and language = '%s' order by id desc", i18n_get_lang());
		$output .= '<center>';
		$output .= '<marquee scrollAmount=3 scrollDelay=3 direction=right>';
		$output .= '<table class="luopin-manu-category-table">';
		$output .= '<tr>';
		while ($row1 = db_fetch_array($result1)) {
			$output .= '<td>';
			if (i18n_get_lang() == 'en') {
				$output .= '<a href="?q=products/machine#' . $row1['id']. '">';
			} else {
				$output .= '<a href="?q=' . i18n_get_lang(). '/products/machine#' . $row1['id']. '">';
			}
			$output .= '<img src="sites/default/files/luopin_manu/' . $row1['picture'] . '" alt=""  width="180" height="120"/>';
			$output .= '</a>';
			$output .= '</td>';
		}
		$output .= '</tr>';
		$output .= '</table>';
		$output .= '</marquee>';
		$output .= '</center>';
		$output .= l(t('Mold & Fixture Products'), 'products/mold');
		$result1 = db_query("select * from luopin_manu_content where category = 'mold_products' and language = '%s' order by id desc", i18n_get_lang());
		$output .= '<center>';
		$output .= '<marquee scrollAmount=3 scrollDelay=3 direction=right>';
		$output .= '<table class="luopin-manu-category-table">';
		$output .= '<tr>';
		while ($row1 = db_fetch_array($result1)) {
			$output .= '<td>';
			if (i18n_get_lang() == 'en') {
				$output .= '<a href="?q=products/mold#' . $row1['id']. '">';
			} else {
				$output .= '<a href="?q=' . i18n_get_lang(). '/products/mold#' . $row1['id']. '">';
			}
			$output .= '<img src="sites/default/files/luopin_manu/' . $row1['picture'] . '" alt=""  width="180" height="120"/>';
			$output .= '</a>';
			$output .= '</td>';
		}
		$output .= '</tr>';
		$output .= '</table>';
		$output .= '</marquee>';
		$output .= '</center>';
	}
	return $output;
}

function luopin_manu_match_path($path, $patterns)
{
	static $regexps;

	if (!isset ($regexps[$patterns])) {
		$regexps[$patterns]= '/^('.preg_replace(array (
						'/(\r\n?|\n)/',
						'/\\\\\*/'
						), array (
							'|',
							'.*'
							), preg_quote($patterns, '/')).')$/';
	}
	$result= preg_match($regexps[$patterns], $path) == 1;
	return $result;
}

/**
 * Callback for luopin_manu/%node menu.
 */
function _luopin_manu_callback($node)
{
	exit ();
}

/**
 * hook_menu implementation.
 */
function luopin_manu_menu()
{
	$items= array ();
	$items['luopin_manu/%node']= array (
			'page callback' => '_luopin_manu_callback',
			'page arguments' => array (
				1
				),
			'type' => MENU_CALLBACK,
			'access arguments' => array (
				'access content'
				)
			);
	return $items;
}
